name: day_end_boxes
description: TooGoodToGo Lebanon - Day-End Boxes Marketplace
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core Flutter packages
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # HTTP Client
  dio: ^5.4.0
  
  # Navigation
  go_router: ^14.2.7
  
  # Localization
  intl: ^0.20.2
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Models & Serialization
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  
  # API Generation
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0
  
  # UI Components
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/translations/
  
  # Fonts - commented out until font files are added
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Inter-Bold.ttf
  #         weight: 700